"""Forward-looking claim evidence (Stage 1).

Narrative source evidence -> `ForwardClaim` -> **nothing yet**. This
package is deliberately a leaf: no module in `analysis_engine`'s
analysis path or in `decision_engine` imports it, so a management
expectation cannot reach Growth, Capital Allocation, Valuation, FCF
Yield, Financial Risk, Outlook, Conviction or Recommendation. The
boundary is enforced by
`tests/unit/analysis_engine/forward_claims/test_integration_safety.py`,
not by convention.
"""
from atlas.analysis_engine.forward_claims.contracts import (
    ClaimBound,
    ClaimRejectionReason,
    ClaimSubject,
    ClaimType,
    ClaimantRole,
    HorizonKind,
)
from atlas.analysis_engine.forward_claims.extraction import (
    EXTRACTOR_VERSION,
    RejectedCandidate,
    classify_claimant,
    extract_forward_claims,
)
from atlas.analysis_engine.forward_claims.models import ForwardClaim
from atlas.analysis_engine.forward_claims.revisions import (
    REVISION_ENGINE_VERSION,
    ClaimComparison,
    GuidanceRevision,
    NonRevisionReason,
    RevisionBasis,
    RevisionEvidence,
    RevisionType,
    compare_claims,
    detect_revisions,
    group_claims,
)
from atlas.analysis_engine.forward_claims.interpretation import (
    INTERPRETATION_VERSION,
    EconomicDimension,
    ExpectedMovement,
    ForwardEvidenceKind,
    GuidanceEconomicInterpretation,
    OutlookEffect,
    interpret_revision,
    interpret_revisions,
)
from atlas.analysis_engine.forward_claims.commitments import (
    LINK_WINDOW,
    CommitmentKind,
    CommitmentStatus,
    CommitmentStatusReading,
    CommitmentSupport,
    CommitmentTerm,
    CommitmentWindow,
    CommittedQuantity,
    CustomerCommitmentClaim,
    SourceEvidenceLink,
    SourceLinkKind,
    read_commitment_status,
)
from atlas.analysis_engine.forward_claims.commitment_links import (
    LINKER_VERSION,
    find_commitment_links,
    link_commitment_sentences,
)
from atlas.analysis_engine.forward_claims.commitment_terms import (
    TERM_READER_VERSION,
    CommitmentEvidence,
    WithheldCommitment,
    WithholdReason,
    commitment_evidence,
    extract_customer_commitments,
    read_commitment_evidence,
)
from atlas.analysis_engine.forward_claims.source_time import period_ordinal, statement_age, transcript_period
from atlas.analysis_engine.forward_claims.synthesis import (
    ALL_ECONOMIC_ASPECTS,
    PICTURE_VERSION,
    SYNTHESIS_VERSION,
    CompanyForwardPicture,
    DimensionState,
    DimensionSummary,
    EconomicAspect,
    EvidenceSpan,
    ForwardEconomicSignal,
    ForwardEconomicSynthesis,
    ForwardStateSignal,
    SignalEntry,
    StateDimension,
    StateDimensionSummary,
    StateObservation,
    describe_company_forward_picture,
    describe_synthesis,
    synthesize_company_forward_picture,
    synthesize_forward_signals,
)
from atlas.analysis_engine.forward_claims.commitment_interpretation import (
    VOLUME_INTERPRETATION_VERSION,
    ContractedVolumeInterpretation,
    VolumeWithholdReason,
    WithheldVolume,
    interpret_customer_commitment,
    interpret_customer_commitments,
)

__all__ = [
    "REVISION_ENGINE_VERSION",
    "ClaimBound",
    "ClaimComparison",
    "GuidanceRevision",
    "NonRevisionReason",
    "RevisionBasis",
    "RevisionEvidence",
    "RevisionType",
    "compare_claims",
    "detect_revisions",
    "group_claims",
    "ClaimRejectionReason",
    "ClaimSubject",
    "ClaimType",
    "ClaimantRole",
    "EXTRACTOR_VERSION",
    "ForwardClaim",
    "HorizonKind",
    "RejectedCandidate",
    "classify_claimant",
    "extract_forward_claims",
    "INTERPRETATION_VERSION",
    "EconomicDimension",
    "ExpectedMovement",
    "ForwardEvidenceKind",
    "SYNTHESIS_VERSION",
    "DimensionState",
    "DimensionSummary",
    "ForwardEconomicSignal",
    "ForwardEconomicSynthesis",
    "SignalEntry",
    "describe_synthesis",
    "synthesize_forward_signals",
    "GuidanceEconomicInterpretation",
    "OutlookEffect",
    "interpret_revision",
    "interpret_revisions",
    "period_ordinal",
    "statement_age",
    "transcript_period",
    "CommitmentKind",
    "CommitmentStatus",
    "CommitmentStatusReading",
    "CommitmentTerm",
    "CommitmentWindow",
    "CommittedQuantity",
    "CustomerCommitmentClaim",
    "read_commitment_status",
    "LINK_WINDOW",
    "CommitmentSupport",
    "SourceEvidenceLink",
    "SourceLinkKind",
    "LINKER_VERSION",
    "find_commitment_links",
    "link_commitment_sentences",
    "TERM_READER_VERSION",
    "CommitmentEvidence",
    "WithheldCommitment",
    "WithholdReason",
    "commitment_evidence",
    "extract_customer_commitments",
    "read_commitment_evidence",
    "ALL_ECONOMIC_ASPECTS",
    "PICTURE_VERSION",
    "CompanyForwardPicture",
    "EconomicAspect",
    "EvidenceSpan",
    "ForwardStateSignal",
    "StateDimension",
    "StateDimensionSummary",
    "StateObservation",
    "describe_company_forward_picture",
    "synthesize_company_forward_picture",
    "VOLUME_INTERPRETATION_VERSION",
    "ContractedVolumeInterpretation",
    "VolumeWithholdReason",
    "WithheldVolume",
    "interpret_customer_commitment",
    "interpret_customer_commitments",
]
