/**
 * Portfolio Import v1.1 — deterministic company-name → ticker dictionary.
 *
 * A maintained, curated lookup — not a fuzzy matcher, and not an attempt
 * at universal coverage. Keys are company names as an investor would
 * type or paste them, normalized (trimmed, lowercased) for lookup;
 * values are the ticker Atlas persists. A name that isn't listed here is
 * never guessed at — `resolveNameToTicker` in `resolution.ts` routes
 * anything unmapped to manual confirmation instead of inventing a match.
 */
export const KNOWN_COMPANY_TICKERS: Readonly<Record<string, string>> = {
  microsoft: "MSFT",
  apple: "AAPL",
  amazon: "AMZN",
  "amazon.com": "AMZN",
  alphabet: "GOOGL",
  google: "GOOGL",
  "meta platforms": "META",
  meta: "META",
  nvidia: "NVDA",
  tesla: "TSLA",
  broadcom: "AVGO",
  "berkshire hathaway": "BRK.B",
  visa: "V",
  mastercard: "MA",
  "johnson & johnson": "JNJ",
  "johnson and johnson": "JNJ",
  "procter & gamble": "PG",
  "procter and gamble": "PG",
  "exxon mobil": "XOM",
  exxonmobil: "XOM",
  "jpmorgan chase": "JPM",
  jpmorgan: "JPM",
  "jp morgan": "JPM",
  walmart: "WMT",
  "eli lilly": "LLY",
  "unitedhealth group": "UNH",
  unitedhealth: "UNH",
  "home depot": "HD",
  salesforce: "CRM",
  adobe: "ADBE",
  netflix: "NFLX",
  "coca-cola": "KO",
  "coca cola": "KO",
  pepsico: "PEP",
  costco: "COST",
  oracle: "ORCL",
  intel: "INTC",
  cisco: "CSCO",
  qualcomm: "QCOM",
  "texas instruments": "TXN",
  "thermo fisher scientific": "TMO",
  abbvie: "ABBV",
  merck: "MRK",
  pfizer: "PFE",
  verizon: "VZ",
  "at&t": "T",
  disney: "DIS",
  "walt disney": "DIS",
  nike: "NKE",
  "mcdonald's": "MCD",
  mcdonalds: "MCD",
  starbucks: "SBUX",
  ibm: "IBM",
  "international business machines": "IBM",
  paypal: "PYPL",
  "booking holdings": "BKNG",
  "booking.com": "BKNG",
  uber: "UBER",
  spotify: "SPOT",
  shopify: "SHOP",
};
